title: CIDVV - Caller-ID Vouching and Vetting
description: Lightweight mechanism to reduce Caller-ID spoofing

theme: jekyll-theme-primer

exclude:
  - draft-anderson-askew-cidvv-latest.md
  - "*.html"
  - "*.txt"
  - "*.pdf"
  - "*.xml"
  - draft/
  - .github
  - Gemfile
  - Gemfile.lock

markdown: kramdown
